### ISSUE TITLE
Can't "click out" of calendar on iOS Safari

### ISSUE THREAD

**Issue by dhruska** [angular-ui/ui-date#110]
I'm working on a project that was built using this directive, and working on fixing a bug as described above. It's possible that it's an issue only with the project I'm working on - has anyone else experienced this? The only way for me to close the date picker is by actually picking a date, when on iOS Safari.

**Comment by alexanderchan** [comment]
Interesting it seems to also happen on the jquery datepicker as well. One option is to enable the done button http://jqueryui.com/datepicker/#buttonbar but that would still require a click. I'd have to investigate further but you may want to also check jquery datepicker issues and stackoverflow to see if someone has resolved it in another way.

**Comment by dhruska** [comment]
Thanks @alexanderchan - if I can't otherwise sort this out it looks like adding a done button might be a good option. I'll add here if I'm able to find any other info.

**Comment by nawlbergs** [comment]
Yea I just implemented his into my app which needs to support ie8 and ios.
I added the button bar via the options.. for ios... and changed the button labels to "Show Today" and "Cancel".

**Comment by dhruska** [comment]
I'm investigating this issue and finding that you can't "click out" of inputs at all on iOS. Go to a website, select an input element, and the only way to escape is to click a link or another input, or click the hide keyboard button, and it appears that blur() is not called when the keyboard is hidden, which is why the calendar stays open.

**Comment by dhruska** [comment]
@alexanderchan In reference to my above comment, I don't think this is a bug and we can probably close this issue out.
