### ISSUE TITLE
momentjs support?

### ISSUE THREAD

**Issue by nawlbergs** [angular-ui/ui-date#114]
I use moment.js because it makes working with dates ridiculously easy.
I added moment.js support to ui-date with very little code. (about 6 lines)
eg... scope passes in a moment() date... scope gets a moment() date back.

Would moment.js support be something that might be implemented in the future?

**Comment by d-rivers** [comment]
Something like this works ok for me:

```javascript
$scope.moment = function(format, value) {
    return moment(value, format).toDate();
};

$scope.dateOptions = {
    minDate: new Date($scope.moment())
};
```

**Comment by nawlbergs** [comment]
that works, yes.  But the value of moment is you ca
