### ISSUE TITLE
using Jquery UI functons??

### ISSUE THREAD

**Issue by LiamKenneth** [angular-ui/ui-date#115]
Hi, how do I use this thing with the Jquery Ui functions like this:

         $('#returnDate').datepicker({
                beforeShowDay: function (date) {
                    var Highlight = SelectedDates[date];
                   
                    if (Highlight) {
                        return [true, "Highlighted", Highlight];
                    }
                    else {
                        return [true, '', ''];
                    }
                }
            });

^this doesn't work with the plugin

**Comment by jkwakman** [comment]
You call the beforeShow, onSelect and onClose handlers. A small example for disabling the sunday: 

    $scope.noSunday = function(element, picker) {
      
    //Get element
    angular.element(element).datepicker('option', 'beforeShowDay', function (date) {
    var day = date.getDay();
         return [(day != 0), ''];
    });
    }

    $scope.dateOptions = {
        beforeShow: function(element, picker) {              
            $scope.noSunday(element, picker);
     },
        minDate: '+2d',
        maxDate: '+1y',
        dateFormat: 'dd-mm-yy',
    };

And add the model to the angular view..

    <input id="date" name="date" ng-model="formData.date" ui-date-format="dd-mm-yy" ui-date="dateOptions">

Hope it helps you out!

**Comment by alexanderchan** [comment]
Thanks for helping here @jkwakman
