### ISSUE TITLE
ui-date 0.0.7 still not working with angular 1.3 when input type="date"

### ISSUE THREAD

**Issue by himdel** [angular-ui/ui-date#116]
The moment you try to use ui-date with an input type="date" it stops working, apearing to show the right value but not setting anything in the model.

Simple test case (tried with angular 1.3, jquery 2.0, jquery-ui 1.11.2 and angular-ui-date 0.0.7) (plunkr is unuseable. sorry):

    <body ng-app="TestApp" ng-controller="TestCtrl">
    	<input ui-date="opt" ng-model="foo">
    	<br />
    	<input type="date" ui-date="opt" ng-model="bar">
    	<br />
    	{{foo.valueOf()}}
    	{{foo|json}}
    	<br />
    	{{bar.valueOf()}}
    	{{bar|json}}
    </body>

 &nbsp;

    angular
    .module('TestApp', [ 'ui.date' ])
    .controller('TestCtrl', function($scope) {
    	$scope.opt = {};
    	$scope.foo = null;
    	$scope.bar = null;
    });

Choosing a date in the first input works fine, `foo` is set to a Date object. In the second, `bar` gets set to undefined.

In chrome I get a `The specified value '02/10/2015' does not conform to the required format, 'yyyy-MM-dd'.` from `jquery.min.js` when I try to set the second input if it's any help. (But chrome support is useless for me becasue that one actually supports input=date so I don't include ui-date there normally.)

**Comment by d-rivers** [comment]
This is actually not supported by jQuery UI Datepicker.
http://api.jqueryui.com/datepicker/
Creating a datepicker on an <input type="date"> is not supported due to a UI conflict with the native picker.

**Comment by alexanderchan** [comment]
thanks @d-rivers for finding that!
