### ISSUE TITLE
ngModel value should not be set if string fail to parse

### ISSUE THREAD

**Issue by randing89** [angular-ui/ui-date#118]
Following test should pass. However currently it sets ngModel value to 'a value'. It violated the statement of `The ui-date directive stores and expects the model value to be a standard javascript Date object.` as a string is not a Date object.

```javascript 
describe('when model is not a Date', function() {
    var element;
    var scope;
    beforeEach(inject(function($compile, $rootScope) {
      element = $compile('<input ui-date="{dateFormat: \'yy-mm-dd\'}" ng-model="x"/>')($rootScope);
      scope = $rootScope;
    }));
    it('should not set value if model fail to parse', function() {
      scope.$apply(function() {
        scope.x = 'a value';
      });
      expect(scope.x).toBeNull();
    });
  });
```

**Comment by alexanderchan** [comment]
It's a good point, we should probably move back towards just keeping a consistent date and not try to support all of the other possibilities to keep it simpler.
