### ISSUE TITLE
If you apply the required directive to element then the form element is invalid until a date is picked.

### ISSUE THREAD

**Issue by sudarshanrao7** [angular-ui/ui-date#132]
If you apply the required directive to element then the form element is invalid until a date is picked.

I needed to set the date from the ngModel when the form loads.The input element has ng-required=true,when i save the form,before using the datepicker,my form validation(required) for the date fails.

To get it to work, i modified your source code,in controller.$render function,right after you set the date "element.datepicker('setDate', date)" , i just needed to call "setVal(); method." This seems to fix my problem.

Is there a easier way to do it without changing the source code(hate to change my grunt tasks/bower install  ;) ), if not do you see any problem with my approach. Can you update the directive in the next version, if possible.

PS: Thanks for the GREAT directive.I extensively use your UI.DATE directive, because unlike other datepicker directives, this one does not create too many unnecessary watches when used inside ngRepeat :+1: 

Thanks,
Sudarshan

**Comment by capesean** [comment]
Are you using Angular 1.4.7? Does it still error with Angular 1.4.0? I seem to have a similar problem that occurs with 1.4.7

**Comment by sudarshanrao7** [comment]
I use angular 1.3.20. But looking at the code, this should happen in angular 1.4.x versions as well

**Comment by alexanderchan** [comment]
hi @sudarshanrao7 can you help by setting up an example of the problem on jsbin or plunkr?  this would be helpful in both seeing the problem and testing the resolution.  Thanks.

**Comment by capesean** [comment]
When I encountered this issue, it happened because the JSON data I was binding to was a ISO8601 Date string, which the datepicker doesn't interpret. So after retrieving the data from the JSON api, I have to convert the model value to a date, ie. `vm.myDate = new Date(vm.myDate);` - then it works fine / validates the initial value.
