### ISSUE TITLE
maxDate and minDate with dateOptions

### ISSUE THREAD

**Issue by fsebbah** [angular-ui/ui-date#133]
Hi,
I follow the directive in the issue #51 , its 'great but if we define a $scope.dateOptions, how it's possible to define both in the directive ui-date.
For sample:
<input ui-date="dateOptions {max:endDate} ng-model="startDate">
<input ui-date="dateOptions {min:endDate max:0} ng-model="startDate">
Thanks,
Franck

**Comment by alexanderchan** [comment]
```html
<input type="text" id="date" ui-date="dateOptions" ng-model="aDate">
```
```javascript 
angular.module('MyModule', ['ui.date']).controller('MyCtrl', function($scope) {
          $scope.aDate = '2015-10-27';
          $scope.dateOptions = {
            dateFormat: 'yy-mm-dd',
            minDate: new Date(),
            maxDate: new Date('2016-01-01')
          }
      })
```
