### ISSUE TITLE
Allow setting of date using ISO8601 date value

### ISSUE THREAD

**Issue by capesean** [angular-ui/ui-date#134]
If you're binding to a model that gets it's data from a JSON api, then the date in the model will be an ISO8601 string. If you are using a display date format, the control will correctly interpret the date and format it to your specification, however it will start as an invalid date until the user picks a new date with the control.

Here's a link to the issue and a plunkr:
http://stackoverflow.com/questions/33344239/angular-ui-datepicker-date-format-from-api/33347669

**Comment by alexanderchan** [comment]
Best to parse to a date format once the data is returned from the api.  Then the model consistently has a date to start.
