### ISSUE TITLE
how to toggle ui-date using a btn

### ISSUE THREAD

**Issue by plus-** [angular-ui/ui-date#14]
I'd like to have an `i.icon-calendar` to toggle the date picker, what is the cleanest way to do it? is there a way to use a `data-toggle` attribute?

**Comment by haffmaestro** [comment]
I used a directive that would look for the input with the ui-date directive on it and then use the datepicker("show") method.
Like so:
```
.directive('showDatePicker',[()=>{
  return {
    restrict: 'A',
    scope: {
      disabled: "=",
      interval: "="
    },
    link: function(scope,element,attrs){
      element.bind("click", function(e){
        if(!scope.disabled){
          angular.element(angular.element(angular.element(element.parent()).children())[1]).datepicker("show")
        }
        if(scope.interval === "monthly"){
          $('.ui-datepicker-header').hide()
        }
        
      })
    }
  }
}])
```

**Comment by BelfordZ** [comment]
Like @haffmaestro said, pretty sure `$('.ui-datepicker-header').hide()` is what you are looking for @plus-

**Comment by alexanderchan** [comment]
hi @BelfordZ thanks for helping support this!  I'm closing this one off.
