### ISSUE TITLE
controller.$validators is undefined

### ISSUE THREAD

**Issue by neekers** [angular-ui/ui-date#146]
I get this error when I update to 0.0.11 from 0.0.3 Not sure why. I'm using a valid JSON date for ng-model and also using

```
 $scope.datePickerOptions = {
     minDate: 0
 }
```

Not sure what to do here.

Error: controller.$validators is undefined
.link/initDateWidget@http://local..com:9000/bower_components/angular-ui-date/src/date.js:140:15
Zd/this.$get</k.prototype.$digest@http://local..com:9000/bower_components/angular/angular.min.js:109:422
Zd/this.$get</k.prototype.$apply@http://local..com:9000/bower_components/angular/angular.min.js:112:396
h@http://local..com:9000/bower_components/angular/angular.min.js:72:452
u@http://local..com:9000/bower_components/angular/angular.min.js:77:463
ye/</z.onreadystatechange@http://local..com:9000/bower_components/angular/angular.min.js:79:24

**Comment by tgkouras** [comment]
Had the same problem when updating from 0.0.7 to 0.0.11, with Angular version 1.2.29.

**Comment by neekers** [comment]
I'm using 1.2.26

**Comment by alexanderchan** [comment]
Sorry I should have updated bower to reflect that angular 1.3.x is
required. If possible can you upgrade and see if that resolves the problems?

On Fri, Dec 11, 2015 at 13:45 Eric Novins <notifications@github.com> wrote:

> I'm using 1.2.26
> On Dec 11, 2015 12:37 PM, "Theo Gkourasas" <notifications@github.com>
> wrote:
>
> > Had the same problem when updating from 0.0.7 to 0.0.11, with Angular
> > version 1.2.29.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/angular-ui/ui-date/issues/146#issuecomment-164041970
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-date/issues/146#issuecomment-164043391>.
>
-- 
Alex Chan
+1-403-707-7174

**Comment by tgkouras** [comment]
@alexanderchan confirmed that there are no errors with angular 1.3.20.  Thanks!

**Comment by alexanderchan** [comment]
@tgkouras thanks for checking, bumped the bower version requirements in the recent beta.
