### ISSUE TITLE
getting NAN

### ISSUE THREAD

**Issue by cameronjroe** [angular-ui/ui-date#147]
I'm setting the `ui-date` directive on an input and getting NAN when selecting a date. If I set type to date, it also throws NAN. Any ideas?
```
<input 
    type="date" 
    ui-date 
    class="form-control" 
    name="date"
    ng-model="showModel.date">
```

**Comment by alexanderchan** [comment]
sorry I can't tell enough from this example without a jsbin or plunkr that reproduces the problem

**Comment by alexanderchan** [comment]
no response, if this issue persists please provide an jsbin/plunkr etc.
