### ISSUE TITLE
Cannot set property 'uiDateValidator' of undefined

### ISSUE THREAD

**Issue by jasenkoh** [angular-ui/ui-date#151]
I'm not sure if it's dependency related or something else but I wasn't able to get rid of the following error:

`TypeError: Cannot set property 'uiDateValidator' of undefined
    at Object.angular.module.constant.constant.factory.directive.link.initDateWidget [as fn] (date.js:140)
    at Scope.$get.Scope.$digest (angular.js:11761)
    at Scope.$get.Scope.$apply (angular.js:12012)
    at done (angular.js:7818)
    at completeRequest (angular.js:7991)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:7947)`

https://github.com/angular-ui/ui-date/blob/master/src/date.js#L141-L144 this snippet is throwing error.

Here's my dependency https://gist.github.com/jasenkoh/9a96093c6f00a9116c20

**Comment by alexanderchan** [comment]
Can you double check the angular version just prior to the execution of the lines?  angular.version.full from console should give you the details

**Comment by jasenkoh** [comment]
@alexanderchan I was able to resolve issue five minutes ago, there was actually line of code that I initially missed:

`"resolutions": {
    "angular": "1.2.6"
}`

I upgraded angular to 1.3.x and also I've upgraded fullcalendar to 2.x, another thing that was causing issue is that I was using moment and jquery-ui had some complains in `_determineDate` method, so I had to intercept those and convert to JS date.

Thank you for quick response.
