### ISSUE TITLE
Empty value is invalid even though it is not required

### ISSUE THREAD

**Issue by Kwaq** [angular-ui/ui-date#152]
I have not required input with ui-date directive which is initially set to null and it is valid.
When I set value and revert it to initial state I expect, that it will be valid, but it is not. UI date validator marks it as invalid.

Example:
[Plunker](http://plnkr.co/edit/t6i6uoLzQzpcDaL2kHjV?p=preview)

**Comment by alexanderchan** [comment]
Should be fixed by #154 please reopen if not
