### ISSUE TITLE
ng-required="false" triggers uiDateValidator error

### ISSUE THREAD

**Issue by theblindfrog** [angular-ui/ui-date#153]
Hi

I'm trying to make an ui-date input conditionally required, buy using `ng-required="someVal === true"`, in conjunction with specify the ui-date options from an object. However, when `ng-required="false"` a `uiDateValidator` error is triggered - when it shouldn't be. That field could be left blank.

e.g. 

```
<form name="someForm">
<input type="text" name="date" ng-required="false" ui-date="dateOptions" ng-model="notReqDate">
</form>
```

where
```
$scope.dateOptions = {
  dateFormat: 'dd/mm/yy'
};
```
triggers a `someForm.$error.uiDateValidator` validation error

Full Example - [JS Bin](http://jsbin.com/loluwexajo)

Is this expected functionality? If so, how do you specify a `dateFormat` while making a field optional?

Thanks

**Comment by alexanderchan** [comment]
@theblindfrog thanks for raising this, it wasn't expected functionality, just a case that needed to be tested.
