### ISSUE TITLE
Using with MongoDB

### ISSUE THREAD

**Issue by anonrig** [angular-ui/ui-date#157]
Hello,

I am using ui-date with MongoDB backend.

My date is: `1992-09-14T21:00:00.000Z`

When I use:

```
<input ui-date ng-model="user.birthDate">
```

The date is set to 2021, not to 1992. Is there a reason for that?

**Comment by alexanderchan** [comment]
This works in the current version 1.0.0 
```
      angular.module('MyApp', ['ui.date'])
      .controller('MyCtrl', function($scope) {
          $scope.aDate = '1992-09-14T21:00:00.000Z';
          $scope.dateOptions = {
             dateFormat: 'dd.mm.yy',
          }
      })
```

**Comment by anonrig** [comment]
![screen shot 2016-03-03 at 9 08 32 pm](https://cloud.githubusercontent.com/assets/1935246/13505923/1d796c46-e184-11e5-94ae-ccd92e55d99f.png)

My date options are: 
```
$scope.dateOptions = {
        dateFormat: 'dd.mm.yy'
    };
```

My html is:
```<div class="field">
                    <label> Doğum Tarihi </label>
                    <input ui-date="dateOptions" ng-model="user.birthDate">

                    {{user.birthDate}}
                </div>```

It doesn't get updated in the view.

**Comment by alexanderchan** [comment]
Try changing to a new Date(valuefromdb) first if your string doesn't match the date format.
