### ISSUE TITLE
How to set Minimum Date and Maximum Date in this ui-date Datepicker

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [angular-ui/ui-date#161]
How can i set minimum date and maximum date in this Datepicker,

> `<input ui-date=""  ng-model="booking_date" class="form-control">`

**Comment by alexanderchan** [comment]
The jquery ui date options should be able to be passed directly through:

```
<input ui-date="{ minDate: -20, maxDate: '+1M +10D' }"/>
```
