### ISSUE TITLE
Version 1.0.0 does not have updated dist

### ISSUE THREAD

**Issue by DukeyToo** [angular-ui/ui-date#162]
See dist js at:
https://github.com/angular-ui/ui-date/blob/1.0.0/dist/date.js#L202-L204

This should be the same null/empty string detection code as
https://github.com/angular-ui/ui-date/blob/1.0.0/src/date.js#L141-L145 

It does not.

**Comment by alexanderchan** [comment]
Thanks, 1.0.1 released

**Comment by gnbonney** [comment]
I don't see a 1.0.1 tag, and there's not a 1.0.1 in bower repository.

**Comment by alexanderchan** [comment]
1.1.1 released
