### ISSUE TITLE
npm says there is a 1.0.1 version, but there is not 1.0.1 tag in github.

### ISSUE THREAD

**Issue by gnbonney** [angular-ui/ui-date#163]
1. Describe the problem and the steps to reproduce
2. Describe the expected result
3. Please create a jsbin/plunkr/etc and preferably non-anonymous so that it does not expire
4. Which version of ui-date/angular are you using?
5. Describe the debugging that has been performed and where in the code you suspect the issue may be
6. Any other useful information?

**Comment by alexanderchan** [comment]
sorry, tagged now.  Need to implement semantic release or a build script to automate this
