### ISSUE TITLE
Need a Angular- UI Date picker where we can select Month and Year in the dropdown.

### ISSUE THREAD

**Issue by idnesh** [angular-ui/ui-date#166]
jQuery has https://jqueryui.com/resources/demos/datepicker/dropdown-month-year.html
Need something similar to this in Angular-UI-DatePicker

**Comment by alexanderchan** [comment]
All jquery datepicker options can be passed to the datepicker. See the options section of the readme for the example.

**Comment by idnesh** [comment]
Thanks.
