### ISSUE TITLE
using datepicker inside ng-repeat

### ISSUE THREAD

**Issue by graphicsxp** [angular-ui/ui-date#39]
I'm using ui-date inside a ng-repeat directive and whenever I use the datepicker, it would only update the input on the first row.  See plunckr for repro : http://plnkr.co/edit/cVarWX?p=preview

What am i doing wrong ?

**Comment by vistasgp888** [comment]
Thanks for posting this.  The same thing just happened to me.  Your answer just saved me lots of frustration.  I'm still new to Angular and I'm not sure why adding an id effects things that way.

**Comment by juddey** [comment]
It saved me a pile of frustration too - thanks alot :)

**Comment by mahammad482** [comment]
Thanks a lot
