### ISSUE TITLE
date in number format causes initial load to the ui element to fail

### ISSUE THREAD

**Issue by pragmatical** [angular-ui/ui-date#44]
I encountered an issue today where I had a date(unix timestamp) which I was receiving seemed to not be binding to a datepicker created with the ui-date directive.  After a bit of testing it looks like the directive does not take into account possibility of the date not being a string but rather a number in the case of ticks, or unix timestamp.  I would propose in the case of the two cases mentioned above where the format of the date is potentially a number, this get handled in the formatter.   See fiddle included.

http://jsfiddle.net/H4NRC/

**Comment by alexanderchan** [comment]
numbers are parsed now but ideally the model should be a date.
