### ISSUE TITLE
Prevent jquery datepicker formatDate exception

### ISSUE THREAD

**Issue by candreoliveira** [angular-ui/ui-date#48]
In my point of view, you must catch the exception in your uiDateFormat directive to prevent the dowdy console error: 

```
TypeError: Object 123 has no method 'getFullYear'
```

The error occurs when you type a malformed string in the input where you apply the ui-date. 

Your directive try to execute (https://github.com/angular-ui/ui-date/blob/master/src/date.js#L99):

```
jQuery.datepicker.formatDate(dateFormat, value);
```

But I think you must execute:

```
modelCtrl.$parsers.push(function(value){
  try{
    if (value)
      return jQuery.datepicker.formatDate(dateFormat, value);                  
  } catch(err) {}
  return null;
});
```

Give permission to PR

**Comment by jualvarez** [comment]
Hello @pragmatical, what is the status of this issue?
I agree with @candreoliveira. I'm getting the same error while the user manually edits the date and while the date is not (yet) valid. This is not something that can be catched in your code base, since it's part of angular's data binding processes. It's triggered because the model's value was changed using a DOM element. Please consider the PR.

**Comment by alexanderchan** [comment]
I think the way this directive validates and parses needs to be updated to use some of the features available since 1.3 and this will resolve many of the errors or invalid data getting propagated to the parsers/model.

**Comment by justinwinslow** [comment]
Bump for this. The solution suggested in the first post seems reasonable. It's not really a _problem_ in the core lib because the ui datepicker prevents "wrong" characters when the plugin is attached to an input via `$( "#datepicker" ).datepicker();`.

**Comment by alexanderchan** [comment]
@justinwinslow in master now I've added a validator instead of throwing errors, there should be another test around this but perhaps you can check if this helps for your case?

**Comment by justinwinslow** [comment]
It still fails here: https://github.com/angular-ui/ui-date/blob/master/src/date.js#L30 when typing into the input.

```
TypeError: date.getFullYear is not a function
    at Datepicker.$.extend.formatDate (datepicker.js:1382)
    at Object.dateToString (date.js:30)
    at Array.<anonymous> (date.js:189)
    at $$parseAndValidate (angular.js:25326)
    at $commitViewValue (angular.js:25316)
    at angular.js:25459
    at Scope.$eval (angular.js:16052)
    at Scope.$apply (angular.js:16152)
    at $$debounceViewValueCommit (angular.js:25458)
    at $setViewValue (angular.js:25430)
```

**Comment by alexanderchan** [comment]
@justinwinslow thanks for your help.  I've reproduced the problem and found a corresponding test for the fix.
