### ISSUE TITLE
datepicker re-opens in IE10

### ISSUE THREAD

**Issue by graphicsxp** [angular-ui/ui-date#8]
when selecting a date in the datepicker, it closes and updates the input value (and the model), but then re-opens right away. This behaviour was noticed in IE10 only. It works fine in other browsers.
The issue was already reported by someone else on stackoverflow: http://stackoverflow.com/questions/15950400/angular-ui-datepicker-wont-close-after-date-selection-in-ie-10

**Comment by JaKXz** [comment]
Any updates on this?

**Comment by alexanderchan** [comment]
Sorry I don't have IE10 installed on my machines and just requested a login to modern.ie.  @JaKXz can you please give your IE and windows versions and create a small jsbin that has this issue for you as this will help in debugging.  PRs are also welcome.

**Comment by neeschit** [comment]
Works fine for me on IE11/Win7

**Comment by smithdalec** [comment]
This is happening for me in IE11/Win7 as well

**Comment by alexanderchan** [comment]
@smithdalec any specific version of ie11?  I don't have ie11 yet so my comment before still applies here that a reproduction somewhere would really help and then I can check against a modern.ie vm.

**Comment by marcelino-m** [comment]
Same issue, all browser ok, but  IE 11 (Version 11.0.9600.18124).

**Comment by marcelino-m** [comment]
What is the purpose of line [123](https://github.com/angular-ui/ui-date/blob/master/src/date.js#L123) in src/date.js??.  Removing this work fine.

**Comment by alexanderchan** [comment]
@marcelino-m Thanks for digging into that, I believe someone had an issue earlier with the input not focusing after close.  If it is sufficient to remove it to fix ie11, we can look at taking it out.

**Comment by olakara** [comment]
@marcelino-m setting `focus(false)` also solves the problem... and works fine for other browsers like FF & Chrome

**Comment by alexanderchan** [comment]
@olakara thanks for the feedback, the problem is that removing focus will make tabbing between fields stop working.  I don't have an easy way off the top of my head to fix both so if anyone has ideas that's great.

I think we will have to remove the focus as suggested though because it is not easy to override this behaviour and if people need to focus they can enhance the onClose option.
