### ISSUE TITLE
Date in UTC format

### ISSUE THREAD

**Issue by fizerkhan** [angular-ui/ui-date#88]
If i select  **07/16/2014** (16th July 2014), it gives a date value as **2014-07-15T18:30:00.000Z**. When i convert this string in server side in UTC format, it gives me one day before date.

**Comment by dmytro-shchurov** [comment]
There is one use case when local-UTC conversions must not happen: DoB. No one expect a timezone in this case. It's and absolute date. Angular's `input[date]` takes this by offering to specify `ng-model-options.timezone`. This option fixes incompleteness of ECMA Date() type.
Check out this
```
ctrl.$parsers.push(function(value) {
      if (ctrl.$isEmpty(value)) return null;
      if (regexp.test(value)) {
        // Note: We cannot read ctrl.$modelValue, as there might be a different
        // parser/formatter in the processing chain so that the model
        // contains some different data format!
        var parsedDate = parseDate(value, previousDate);
        if (timezone === 'UTC') {
          parsedDate.setMinutes(parsedDate.getMinutes() - parsedDate.getTimezoneOffset());
        }
        return parsedDate;
      }
      return undefined;
    });

    ctrl.$formatters.push(function(value) {
      if (value && !isDate(value)) {
        throw $ngModelMinErr('datefmt', 'Expected `{0}` to be a date', value);
      }
      if (isValidDate(value)) {
        previousDate = value;
        if (previousDate && timezone === 'UTC') {
          var timezoneOffset = 60000 * previousDate.getTimezoneOffset();
          previousDate = new Date(previousDate.getTime() + timezoneOffset);
        }
        return $filter('date')(value, format, timezone);
      } else {
        previousDate = null;
        return '';
      }
    });
```

I expect something similar to this with the date picker

**Comment by alexanderchan** [comment]
@dmytro-shchurov thanks for this feedback, I'll try to check this out when I get a chance but PRs with tests are welcome if you have any time.

**Comment by harsh5400** [comment]
Hi

I need a absolute date from the date picker. Is there any possibilities. I do not want to convert the date between different time zone

**Comment by harsh5400** [comment]
Hi Guys I Solved this issue u need to change the date to localestring in date directive(date.js) as shown below.

//Old Code:  controller.$setViewValue(element.datepicker('getDate'));

//Change Code:
  var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
 controller.$setViewValue(element.datepicker('getDate').toLocaleString("en-GB", options));

Thanks
